### PR TITLE
fix the links of v1.3.1 docs

### PR DESCRIPTION
**Pull request by karuppiah7890**

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Even the links of 1.4.1 say `dev` instead of `stable` 🤔

**Comment by filiphr** [comment]
Good spot @karuppiah7890, thanks for the PR. 

>Even the links of 1.4.1 say `dev` instead of `stable` or just `1.4` 🤔

This is on purpose, we do not publish snapshot documentation. This means that `dev` is the last release. So during the 1.4 Beta and CR phases it was pointing to 1.4. Line 15 and 16 should be changed to `stable` now. I forgot to do that. Would you like to do that as well, or shall I merge this as is and fix it?

**Comment by karuppiah7890** [comment]
I'll change it to `stable` :)

**Comment by karuppiah7890** [comment]
Done! 👍

**Comment by filiphr** [comment]
Thanks a lot. It will be up online in few minutes

**Pull request merged**
