### PR TITLE
#37 "Edit on GitHub" link

### PR DESCRIPTION
**Pull request by gunnarmorling**
@agudian Want to test your double-click fu?

### CODE REVIEW

**Comment by agudian** [comment]
Hell yeah!

**Comment by gunnarmorling** [comment]
@agudian seems something went wrong, the generated links are broken. Somehow a backslash got in there :(

**Comment by agudian** [comment]
Trying to fix it... I guess building it on Windows takes the OS path seperator for `.File.Path`

**Comment by gunnarmorling** [comment]
Yeah, something like that. Actually perfect that you are handling this PR, otherwise it would have easily went unnoticed if you had merged another change in the future.

**Pull request merged**
