### PR TITLE
Add page Documentation->IDE Support

### PR DESCRIPTION
**Pull request by agudian**
@gunnarmorling, you're right, it is fun with Hugo!

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Cool, glad to hear! What about that HAML file. It's some left-over, I reckon?

**Comment by agudian** [comment]
> It's some left-over, I reckon?

Yeah, that was what I had on my old branch... 👍

**Comment by gunnarmorling** [comment]
It's up, thanks! Note that I've changed it to use the `{{< prettify >}}` shortcode in order to benefit from nice highlighting and line numbers.

**Comment by agudian** [comment]
Nice, thanks!

**Pull request closed without merging**
