### PR TITLE
Blog post about Filip taking over as project lead

### PR DESCRIPTION
**Pull request by gunnarmorling**
@filiphr @agudian @sjaakd Here's the blog post about the project lead change. Let me know what you think. Is it too long perhaps? Thanks for any feedback!

### CODE REVIEW

**Comment by agudian** [comment]
I think it’s great, Gunnar!

**Comment by sjaakd** [comment]
It is..Nice piece. And end of an era sigh..

**Comment by gunnarmorling** [comment]
Thanks, @agudian and @sjaakd. After talking to Sabine, I've re-arranged things a bit now, putting the most important info about the change and Filips great contributions first, and the look back after that.

> And end of an era sigh..

Well, I'm still around, so you won't get rid of me completely :)

But indeed it's a bit of an odd feeling for me, too. Anyways, I'm sure MapStruct will do just fine thanks to its fantastic community with great folks like you here!

**Comment by filiphr** [comment]
❤️ really good write up @gunnarmorling. Again thanks to all of you for the trust in me 😄.

>Well, I'm still around, so you won't get rid of me completely :)

I would never want that too happen 😉 

On a side note, I think you committed this change directly. Should we close this?

**Comment by gunnarmorling** [comment]
> Again thanks to all of you for the trust in me

It's well deserved 😄 

>  Should we close this?

Yep, doing it right now.

**Pull request closed without merging**
