### PR TITLE
Add description for Filip

### PR DESCRIPTION
**Pull request by filiphr**
And fix typo in @sjaakd description 😄. I can remove the typo if it is my mistake.

### CODE REVIEW

**Comment by agudian** [comment]
Hey, cool!

Just a hint: I'd leave out the part with the three years - soon enough it'll be outdated and you'll probably forget to update that part 😁

**Comment by filiphr** [comment]
You are right, I removed that 😄

**Comment by agudian** [comment]
Will you merge it and publish the site yourself?

**Comment by sjaakd** [comment]
> Fix typo in Sjaak's description

So typically me 👍

**Comment by filiphr** [comment]
I'll merge and try the publishing 😄

**Comment by filiphr** [comment]
All done 😄

**Pull request merged**
